version: "3.9"

services:
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_DATABASE: ludus
      MARIADB_USER: ludus
      MARIADB_PASSWORD: ludus
      MARIADB_ROOT_PASSWORD: toor
  adminer:
    image: adminer:latest
    depends_on:
      - database
    ports:
      - 8100:8080
    restart: always
  arena:
    image: colosseum-project/arena:latest
    ports:
      - 8082:8082
    restart: always
  podium:
    image: colosseum-project/podium:latest
    ports:
      - 8083:8083
    restart: always
  ludus:
    depends_on:
      - database
      - arena
    image: colosseum-project/ludus:latest
    ports:
      - 8081:8081
    restart: always
    environment:
      DB_URL: jdbc:mariadb://database:3306/ludus
      DB_USERNAME: ludus
      DB_PASSWORD: ludus
      ARENA_ENDPOINT: http://arena:8082
  bisellium:
    depends_on:
      - arena
      - podium
      - ludus
    image: colosseum-project/bisellium:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      LUDUS_ENDPOINT: http://ludus:8081
      ARENA_ENDPOINT: http://arena:8082
      PODIUM_ENDPOINT: http://podium:8083

volumes:
  data:
