---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arena
spec:
  selector:
    matchLabels:
      app: arena
  replicas: 2
  template:
    metadata:
      name: arena
      labels:
        app: arena
    spec:
      containers:
      - name: arena
        image: docker.io/voudoo/arena:latest
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: colosseum-apps-config
---
apiVersion: v1
kind: Service
metadata:
  name: arena-service
spec:
  type: ClusterIP
  selector:
    app: arena
  ports:
  - name: http
    port: 8082
