---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ludus
spec:
  selector:
    matchLabels:
      app: ludus
  replicas: 1
  template:
    metadata:
      name: ludus
      labels:
        app: ludus
    spec:
      containers:
      - name: ludus
        image: docker.io/voudoo/ludus:latest
        envFrom:
        - configMapRef:
            name: colosseum-apps-config
        - secretRef:
            name: ludus-config
---
apiVersion: v1
kind: Service
metadata:
  name: ludus-service
spec:
  type: ClusterIP
  selector:
    app: ludus
  ports:
  - name: http
    port: 8081
