---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    project: colosseum
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      name: mariadb
      labels:
        app: mariadb
        tier: frontend
    spec:
      containers:
        - name: mariadb
          image: docker.io/mariadb:latest
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: MARIADB_DATABASE
              value: "ludus"
            - name: MARIADB_USER
              value: "ludus"
            - name: MARIADB_PASSWORD
              value: "ludus"
            - name: MARIADB_ROOT_PASSWORD
              value: "toor"
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - name: mariadb-port
      port: 3306
