---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arena
  labels:
    project: colosseum
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app: arena
  replicas: 2
  template:
    metadata:
      name: arena
      labels:
        app: arena
        tier: frontend
    spec:
      containers:
        - name: arena
          image: docker.io/voudoo/arena:latest
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "128Mi"
              cpu: "80m"
---
apiVersion: v1
kind: Service
metadata:
  name: arena-service
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: arena
  ports:
    - name: http
      port: 8082
