apiVersion: apps/v1
kind: Deployment
metadata:
  name: ludus
  labels:
    project: colosseum
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app: ludus
  replicas: 1
  template:
    metadata:
      name: ludus
      labels:
        app: ludus
        tier: backend
    spec:
      containers:
        - name: ludus
          image: docker.io/voudoo/ludus:latest
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: DB_URL
              value: "jdbc:mariadb://mariadb-service:3306/ludus"
            - name: DB_USERNAME
              value: "ludus"
            - name: DB_PASSWORD
              value: "ludus"
            - name: ARENA_ENDPOINT
              value: "http://arena-service:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: ludus-service
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: ludus
  ports:
    - name: http
      port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ludus-service-external
  namespace: sandbox
spec:
  type: NodePort
  selector:
    app: ludus
  ports:
    - name: http
      port: 8081
      nodePort: 30001
