---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podium
  labels:
    project: colosseum
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app: podium
  replicas: 2
  template:
    metadata:
      name: podium
      labels:
        app: podium
        tier: frontend
    spec:
      containers:
        - name: podium
          image: docker.io/voudoo/podium:latest
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "128Mi"
              cpu: "80m"
          env:
            - name: LUDUS_ENDPOINT
              value: "http://ludus-service:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: podium-service
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: podium
  ports:
    - name: http
      port: 8083
