---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bisellium
spec:
  selector:
    matchLabels:
      app: bisellium
  replicas: 2
  template:
    metadata:
      name: bisellium
      labels:
        app: bisellium
    spec:
      containers:
      - name: bisellium
        image: docker.io/voudoo/bisellium:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: colosseum-apps-config
---
apiVersion: v1
kind: Service
metadata:
  name: bisellium-service-external
spec:
  type: NodePort
  selector:
    app: bisellium
  ports:
  - name: http
    port: 8080
    nodePort: 30000
