apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: colosseum
resources:
- configmap.yaml
- arena.yaml
- podium.yaml
- ludus.yaml
- bisellium.yaml
secretGenerator:
- name: ludus-database-config
  envs:
  - database.env
