---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ludus
spec:
  selector:
    matchLabels:
      app: ludus
  replicas: 1
  template:
    metadata:
      name: ludus
      labels:
        app: ludus
        tier: backend
    spec:
      containers:
        - name: ludus
          image: docker.io/voudoo/ludus:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: DB_URL
              value: "jdbc:mariadb://mariadb-service:3306/ludus"
            - name: DB_USERNAME
              value: "ludus"
            - name: DB_PASSWORD
              value: "ludus"
            - name: ARENA_ENDPOINT
              value: "http://arena-service:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: ludus-service
spec:
  type: ClusterIP
  selector:
    app: ludus
  ports:
    - name: http
      port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ludus-service-external
spec:
  type: NodePort
  selector:
    app: ludus
  ports:
    - name: http
      port: 8081
      nodePort: 30001
