---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podium
spec:
  selector:
    matchLabels:
      app: podium
  replicas: 2
  template:
    metadata:
      name: podium
      labels:
        app: podium
        tier: frontend
    spec:
      containers:
        - name: podium
          image: docker.io/voudoo/podium:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: colosseum-config
---
apiVersion: v1
kind: Service
metadata:
  name: podium-service
spec:
  type: ClusterIP
  selector:
    app: podium
  ports:
    - name: http
      port: 8083
