@hostname = localhost
@port = 8081
@host = {{hostname}}:{{port}}
@contentType = application/json

###

# @name = resolveDuel
# @prompt FirstGladiatorId
# @prompt SecondGladiatorId
POST http://{{host}}/duels/resolve
    ?first_gladiator_id={{FirstGladiatorId}}
    &second_gladiator_id={{SecondGladiatorId}}
Content-Type: {{contentType}}

###

# @name = resolveRandomDuel
POST http://{{host}}/duels/resolve/random
Content-Type: {{contentType}}
